### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by waweic** [dnet/adsdroid#11]
I translated you App to German using Stringlate:

https://gist.github.com/anonymous/cbb84578414097a68fab967be3f55f38

**Comment by dnet** [comment]
Thanks, just a question: the `Spinner` (also known as a drop-down list on PCs) that lets you select the search mode cannot be translated at the moment, as it's generated at runtime by `hu.vsza.adsapi.Search.Mode.toString()`, not loaded from string resources like everything else on the UI. Would you consider this a problem for German users?

**Comment by dnet** [comment]
To clarify, the UI would look like this for people with Germal locale: `Suchmodus: [includes ▼]`

**Comment by waweic** [comment]
I don't think this could be a problem in any way. I think, 99% of german Users of your app should be able to understand the entries in the spinner.

**Comment by dnet** [comment]
Released [v1.6.2](https://github.com/dnet/adsdroid/releases/tag/v1.6.2) with this included.
