### ISSUE TITLE
cannot download your app

### ISSUE THREAD

**Issue by lecciovich** [dnet/adsdroid#13]
I was trying to download your app from fdroid but occurs a message like this 
https://f-droid.org/repo/hu.vsza.adsdroid_8.apk https://f-droid.org/repo/hu.vsza.adsdroid_8.apk
and download doesnt start
What can i do?
Thank you for the attention
Marco

**Comment by dnet** [comment]
I don't have any affiliation with F-droid, they just host my app. If you
have problems installing the app from there, contact them.

You can also download the app from here on GitHub in the releases page.

https://github.com/dnet/adsdroid/releases

**Comment by lecciovich** [comment]
Thank you very much for the quick answer
I'll try
Regards
Marco


Il 16 lug 2017 12:15, András Veres-Szentkirályi <notifications@github.com> ha scritto:
I don't have any affiliation with F-droid, they just host my app. If you
have problems installing the app from there, contact them.

You can also download the app from here on GitHub in the releases page.

https://github.com/dnet/adsdroid/releases
