### ISSUE TITLE
Error fetching results

### ISSUE THREAD

**Issue by fastyzfr1** [dnet/adsdroid#4]
No matter what I search for, I get "Error fetching results"

**Comment by alex1702** [comment]
That error is in logcat
https://p.elaon.de/Akwqgi/

**Comment by dnet** [comment]
Thanks, please also include what you did when this happened (startup, search, datasheet download, etc.) your Android OS version and indicate where you got your binary from. (F-Droid, vsza.hu, built for yourself, etc.)

**Comment by alex1702** [comment]
Search. Android 5.1.1 paranoid Android and fdroid. Version 1.5.1

**Comment by alex1702** [comment]
Habe you a solution for the Problem?

**Comment by dnet** [comment]
I managed to reproduce the issue with a debug version in emulator, stay tuned!

**Comment by dnet** [comment]
Try this version, it seemed to work fine on my emulator: http://vsza.hu/adsdroid-gh4-20150915.apk
(This is signed with the same key as the ones on vsza.hu, but different from the F-Droid key -- which I obviously have no access to -- so if you installed from latter, you might have to uninstall that first.)

Let me know if it fixed your issue!

**Comment by alex1702** [comment]
Work perfect

**Comment by dnet** [comment]
Thanks for testing, I pushed the code to GitHub, so F-Droid should have it soon.
