### ISSUE TITLE
Multiple results for the same part

### ISSUE THREAD

**Issue by felicitus** [dnet/adsdroid#5]
Example :when searching for atmega168, the last includes 4 results for ATMEGA168-20 with no indication what the differences might be.

**Comment by timofonic** [comment]
Sorry to open an old topic, but still happens to some ambiguous names. Sometimes the same part appear waive because of a different manufacturer or it contains part of the code.

**Comment by dnet** [comment]
For latter, you could search for exact matches and two other options by using the dropdown list (Spinner in Android terms) on the search page. See [Search.Mode](https://github.com/dnet/adsdroid/blob/master/src/hu/vsza/adsapi/Search.java#L12)

For the former, should the result page include manufacturer? I found no use for it, but if it's necessary, I could include it I guess (but it's not trivial with that soup of HTML tags that they call website).
